spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: DEBUG
    ma.fstt.authentificationservice: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG


