spring:
  config:
    activate:
      on-profile: prod


logging:

  level:
    root: INFO
    ma.fstt.authentificationservice: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO


