spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
    org.springframework.web.cors: INFO
    root: INFO