spring:
  datasource:
    url: ${PROD_DB_NOTIFICATION_URL:jdbc:mysql://localhost:3306/notifications}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${PROD_DB_USERNAME:root}
    password: ${PROD_DB_PASSWORD:root}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicExtractor: TRACE
